### ISSUE TITLE
Magento 2 Commerce Cloud

### ISSUE THREAD

**Issue by rafagaseo** [dholidev/module-dholi-payu-mirror#1]
Esse módulo atende também a versão Commerce Cloud (Enterprise) do Magento 2?

**Comment by dholidev** [comment]
Ráfaga, tudo bem?

Nós ainda não testamos no Enterprise, o foco inicial é o CE.

O módulo foi construído usando o Payment Provider Gateway (https://devdocs.magento.com/guides/v2.3/payments-integrations/payment-gateway/payment-gateway-intro.html), uma mudança radical na forma de finalizar as compras. Acredito que o Enterprise use o mesmo motor.

Se você tiver interesse podemos ver uma maneira de colocamos no Enterprise. Podemos falar sobre.

Se quiser trocar uma idéia, me manda uma mensagem no Whats (51) 99825-8774.

Abraço.

**Comment by rafagaseo** [comment]
Obrigado pela resposta @dholidev. Parabéns pelo trabalho, acredito que podemos evoluir uma conversa.
Abraço e sucesso.

**Comment by dholidev** [comment]
Obrigado.

Att.
Rodrigo.

**Comment by dholidev** [comment]
Oi Ráfaga, tudo bem?

foi pro ar na semana passada a loja da https://nuspace.com.br/. Está usando nosso módulo Open Source com a PayU. Está 100% OK com o OSC da Amasty e checkout nativo Magento >= 2.3.2.

A interação com o novo padrão de pagamento do Magento 2 ficou muito "foda".

Caso queiram testar no CC, podem usar esse convênio de teste "http://docs.dholi.dev/payu/configuracao".

* temos integração com a Jadlog do Almir aí em Itajaí, caso apareça algo.

Se precisarem de algo, podem chamar.

Abraço.

**Comment by rafagaseo** [comment]
Fala Dholi.

Muito legal cara. Nós estamos em um ritmo muito forte de projetos e temos
muita coisa legal entrando, enviei seu email para gestor de projeto e
estrategistas aqui da Híbrido, porque eles sempre estão atentos a
necessidades dos clientes.

Com certeza vamos utilizar teus módulos e o que puder ajudar conte comigo.

Sucesso.


<http://www.souhibrido.com.br/?utm_source=assinatura&utm_medium=e-mail&utm_campaign=rafaga>

Ráfaga Gianesini

Analistas de Novos Negócios

rafaga@souhibrido.com.br

www.hibrido.com.br
<http://www.hibrido.com.br/?utm_source=assinatura&utm_medium=e-mail&utm_campaign=rafaga>


Em ter., 14 de jan. de 2020 às 00:40, Dholi <notifications@github.com>
escreveu:

**Comment by dholidev** [comment]
Oi Ráfaga, tudo bem?

Te mandei um email. Dá uma olhada se caiu no spam.

Abraço.

**Comment by rafagaseo** [comment]
Já respondi!

Obrigado mestre.
<http://www.souhibrido.com.br/?utm_source=assinatura&utm_medium=e-mail&utm_campaign=rafaga>

Ráfaga Gianesini

Analistas de Novos Negócios

rafaga@souhibrido.com.br

www.hibrido.com.br
<http://www.hibrido.com.br/?utm_source=assinatura&utm_medium=e-mail&utm_campaign=rafaga>


Em qua., 29 de jan. de 2020 às 14:57, Dholi <notifications@github.com>
escreveu:
